Minor installer text changes
CosmoQuestX/CSB7.0 pull request #149
Opened 2022-08-23 20:10 UTC by KeeperOfMaps

** Description **
Tweaked text in the installer related to the PHP requirements

** Fixed issue(s) **

** (optional) Notable changes **

2022-08-24 05:48 UTC, dpi209 requested changes
Sorry to say, but: 

Line 263: This makes less sense than the previous version since it outputs the version it checks against, not the installed one. You suggested "PHP Version above" when we chatted, that would probably be the best. 

Line 322: You couldn't tell from the version we tested against whether the next minor version would work, since we don't know whether PHP will introduce breaking changes in their next version. We should be safe for at least one minor version, since they usually deprecate before removing and warn before changing. On the other hand, their next version could be a major version and still be fine. Thinking of it, the previous version was equally wrong. I don't know how to phrase it less wrong, though.

2022-08-24 22:55 UTC, KeeperOfMaps commented
I have made changes to the wording for both the verification message and the requirements on the right side.

There may be future work needed on the version displayed.

2022-08-24 23:11 UTC, KeeperOfMaps commented
Version confirmation message should now display the currently installed version.

2022-08-25 11:14 UTC, dpi209 approved these changes

2022-08-25 12:49 UTC, merged